workflows:
  ios-app-store:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - Stela Team
    # integrations:
    #   app_store_connect: codemagic
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS app for simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true
    #     submit_to_app_store: false
