workflows:
  ios-app-store:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - Stela Team
    integrations:
      app_store_connect: codemagic
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Set up signing certificate
        script: |
          PRIVATE_KEY=$(echo "$APP_STORE_CONNECT_PRIVATE_KEY" | tr -d '\n')
          app-store-connect fetch-signing-files --issuer-id $APP_STORE_CONNECT_ISSUER_ID --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER --private-key "$PRIVATE_KEY" --certificate-key $APPLE_DEVELOPER_CERTIFICATE --certificate-key-password $APPLE_DEVELOPER_CERTIFICATE_PASSWORD --type IOS_APP_STORE com.stelanetwork.app
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build ipa for App Store
        script: |
          flutter build ipa --release \
            --build-name=1.0.3 \
            --build-number=$(($(app-store-connect get-latest-build-number "$APP_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
